### ISSUE TITLE
Sélection de race

### ISSUE THREAD

**Issue by Esetan** [AngelsMari/Lupino#16]
**En tant que** joueur 
**Je souhaiterais** voir une plus grande différence lorsque je sélectionne une race pour mon personnage (plus de contraste de couleur)
**Afin de** pouvoir m'assurer plus facilement de la bonne sélection de celle-ci

**Comment by Esetan** [comment]
Possible de juste supprimer les images pour le moment : le menu races de la catégorie univers marche très bien

**Comment by AngelsMari** [comment]
Remarque remonté par 2 utilisateurs différentes, sera déployé prochaine mise à jour
