### ISSUE TITLE
Création de nouveaux objets

### ISSUE THREAD

**Issue by Esetan** [AngelsMari/Lupino#19]
**En tant que** MJ
**Je souhaiterais** pouvoir ajouter de nouveaux objets dans la dite catégorie
**Afin de** permettre aux joueurs d'accéder à plus d'items lors de leur création de personnage

**Comment by AngelsMari** [comment]
Rejoins la liste de gestion des utilisateurs, cette fonctionnalité est disponible mais que pour les admins, il faudrait pouvoir ajouter un utilisateur en admin. Voir #5
